name: Build bs-emotion-ppx release

trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - "*" # must quote since "*" is a YAML reserved character; we want a string

jobs:
  - job: bs-emotion
    displayName: Build bs-emotion
    template: build-bs-emotion.yml
    parameters:
      platform: macOS
      vmImage: macOS-10.13

  - job: bs-emotion-ppx-linux
    displayName: Build bs-emotion-ppx (Linux)
    template: bs-emotion-ppx/build-platform.yml
    parameters:
      platform: Linux
      vmImage: ubuntu-16.04

  - job: bs-emotion-ppx-macos
    displayName: Build bs-emotion-ppx (macOS)
    template: bs-emotion-ppx/build-platform.yml
    parameters:
      platform: macOS
      vmImage: macOS-10.13

  # Need windows-2019 to do esy import/export-dependencies
  # which assumes you have bsdtar (tar.exe) in your system
  # otherwise it will end up using the esy-bash tar which doesn't
  # understand drives like D:/ (thinks it's an scp path).
  - job: bs-emotion-ppx-windows
    displayName: Build bs-emotion-ppx (Windows)
    template: bs-emotion-ppx/build-platform.yml
    parameters:
      platform: Windows
      vmImage: windows-2019

  # This job is kept here as we want to have the platform names in the same file
  - job: Release
    displayName: Release
    dependsOn:
      - Linux
      - macOS
      - Windows
    pool:
      vmImage: macOS-10.13
      demands: node.js
    steps:
      - template: bs-emotion-ppx/cross-release.yml
