name: Build bs-emotion-ppx

on: [push, pull_request]

defaults:
  run:
    shell: bash
    working-directory: bs-emotion-ppx

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: Install esy
        run: npm install -g esy
        
      - name: Try to restore install cache
        uses: actions/cache@v1
        with:
          path: ~/.esy/source
          key: source-${{ hashFiles('**/index.json') }}

      - name: Install
        run: esy install

      - name: Print esy cache
        id: print_esy_cache
        run: |
          cd ..
          node .github/workflows/print_esy_cache.js

      - name: Try to restore build cache
        id: deps-cache-macos
        uses: actions/cache@v1
        with:
          path: ${{ steps.print_esy_cache.outputs.esy_cache }}
          key: build-${{ matrix.os }}-${{ hashFiles('**/index.json') }}
          restore-keys: build-${{ matrix.os }}-

      - name: Build
        run: esy build

      - name: '[Test] esy install'
        run: esy install
        working-directory: bs-emotion-ppx/test
        env:
          CI: true

      - name: '[Test] esy build'
        run: esy install
        working-directory: bs-emotion-ppx/test
        env:
          CI: true

      - name: '[Test] yarn install'
        run: esy install
        working-directory: bs-emotion-ppx/test
        env:
          CI: true

      - name: '[Test] yarn build'
        run: esy install
        working-directory: bs-emotion-ppx/test
        env:
          CI: true

      - name: Release
        run: esy release-static

      - name: Upload artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: bs-emotion-ppx/_build/default/bin/BsEmotionPpx.exe

      - name: Cleanup
        run: |
          # Cleanup build cache in case dependencies have changed
          esy cleanup .
